openapi: 3.0.3
info:
  title: Shopper Experience
  version: v1
  description: |-
    Use the Shopper Experience API to look up page information for pages that are created in Page Designer.

    Responses include the following:

    - The entire component hierarchy of the page at design time.
    - All merchant data provided at design time.
    - Server-side scripting data provided at run time.

    Both the page and components contain the values of all native and custom attributes that have been populated during page authoring.

    Only visible pages are returned. Because the visibility of components is driven by rules (scheduling or customer groups, for example), these rules are subject to evaluation when assembling the component hierarchy in the response. Only components that are visible for the current customer context appear in the response. The same rules apply to the page itself, which is only be processed and returned if it is visible.

    **Important**: Currently, the Shopper Experience API canâ€™t be used when the [storefront password protection](https://documentation.b2c.commercecloud.salesforce.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2Fcontent%2Fb2c_commerce%2Ftopics%2Fpermissions%2Fb2c_storefront_password_protection.html&resultof=%22%73%74%6f%72%65%66%72%6f%6e%74%22%20%22%70%72%6f%74%65%63%74%69%6f%6e%22%20%22%70%72%6f%74%65%63%74%22%20) feature is enabled.

    ## Authentication & Authorization

    The Shopper Experience API requires a shopper access token from the Shopper Login and API Access Service (SLAS).

    For details on how to request a shopper access token from SLAS, see the guest user flows for [public clients](https://developer.salesforce.com/docs/commerce/commerce-api/guide/slas-public-client.html#guest-user) and [private clients](https://developer.salesforce.com/docs/commerce/commerce-api/guide/slas-private-client.html#guest-user) in the SLAS guides.

    You must include the relevant scope(s) in the client ID used to generate the SLAS token. For details, see the [Authorization Scopes Catalog.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/auth-z-scope-catalog.html).
servers:
  - url: https://{shortCode}.api.commercecloud.salesforce.com/experience/shopper-experience/v1
    variables:
      shortCode:
        default: shortCode
paths:
  /organizations/{organizationId}/pages:
    get:
      summary: Get Page Designer pages.
      description: "Get Page Designer pages. The results apply the visibility rules for each page's components, such as personalization or scheduled visibility.\n\nYou must provide the `aspectTypeId` along with either a `categoryId` or a `productId`. Since you can only create one page-to-product or page-to-category assignment per aspect type, the result contains at most one element.\n\n**Important**: \n- Currently, you can't use the Shopper Experience API when the [storefront password protection](https://documentation.b2c.commercecloud.salesforce.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2Fcontent%2Fb2c_commerce%2Ftopics%2Fpermissions%2Fb2c_storefront_password_protection.html&resultof=%22%73%74%6f%72%65%66%72%6f%6e%74%22%20%22%70%72%6f%74%65%63%74%69%6f%6e%22%20%22%70%72%6f%74%65%63%74%22%20) feature is enabled.\n- Because this resource uses the GET method, you must not pass sensitive data, for example: payment card information, and must not perform transactional processes within the server-side scripts that are run for the page and components.\n- Be aware that pagecache during fingerprint calculation will only be leveraged for pages and their components that don't use visibility rules. Furthermore the pagecaching of the actual response assembly solely depends on the response instrumentation with the serverside page type and component type script implementations. For more details also see the [Page Designer Caching Guide](https://developer.salesforce.com/docs/commerce/b2c-commerce/guide/b2c-dev-for-page-designer.html#page-caching)."
      operationId: getPages
      parameters:
        - $ref: '#/components/parameters/organizationId'
        - $ref: '#/components/parameters/categoryId'
        - $ref: '#/components/parameters/productId'
        - $ref: '#/components/parameters/aspectTypeId'
        - $ref: '#/components/parameters/aspectAttributes'
        - $ref: '#/components/parameters/parameters'
        - $ref: '#/components/parameters/siteId'
        - $ref: '#/components/parameters/locale'
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResult'
              examples:
                PageResult:
                  $ref: '#/components/examples/PageResult'
        '400':
          description: |
            Business Object ID Invalid
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                BusinessObjectIDInvalid:
                  $ref: '#/components/examples/BusinessObjectIDInvalid'
        '404':
          description: |
            Requested Aspect Type Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                AspectTypeNotFound:
                  $ref: '#/components/examples/AspectTypeNotFound'
      security:
        - ShopperToken:
            - sfcc.shopper-experience
  /organizations/{organizationId}/pages/{pageId}:
    get:
      summary: Get a Page Designer page based on a single page ID.
      description: "Get a Page Designer page for a specific page ID. The results apply the visibility rules for the page's components, such as personalization or scheduled visibility.\n\n**Important**: \n- Currently, you can't use the Shopper Experience API when the [storefront password protection](https://documentation.b2c.commercecloud.salesforce.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2Fcontent%2Fb2c_commerce%2Ftopics%2Fpermissions%2Fb2c_storefront_password_protection.html&resultof=%22%73%74%6f%72%65%66%72%6f%6e%74%22%20%22%70%72%6f%74%65%63%74%69%6f%6e%22%20%22%70%72%6f%74%65%63%74%22%20) feature is enabled.\n- Because this resource uses the GET method, you must not pass sensitive data, for example: payment card information, and must not perform transactional processes within the server-side scripts that are run for the page and components.\n- Be aware that pagecache during fingerprint calculation will only be leveraged for pages and their components that don't use visibility rules. Furthermore the pagecaching of the actual response assembly solely depends on the response instrumentation with the serverside page type and component type script implementations. For more details also see the [Page Designer Caching Guide](https://developer.salesforce.com/docs/commerce/b2c-commerce/guide/b2c-dev-for-page-designer.html#page-caching)."
      operationId: getPage
      parameters:
        - $ref: '#/components/parameters/pageId'
        - $ref: '#/components/parameters/organizationId'
        - $ref: '#/components/parameters/aspectAttributes'
        - $ref: '#/components/parameters/parameters'
        - $ref: '#/components/parameters/siteId'
        - $ref: '#/components/parameters/locale'
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'
              examples:
                Page:
                  $ref: '#/components/examples/Page'
        '400':
          description: |
            Provided Aspect Attribute Invalid
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                AspectAttributeInvalid:
                  $ref: '#/components/examples/AspectAttributeInvalid'
        '404':
          description: |
            Requested Page Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                PageNotFound:
                  $ref: '#/components/examples/PageNotFound'
      security:
        - ShopperToken:
            - sfcc.shopper-experience
components:
  securitySchemes:
    ShopperToken:
      type: oauth2
      description: "ShopperToken authentication follows the authorization code grant flow, as defined by the OAuth 2.1 standard. Depending on the type of OAuth client (public or private), this authorization flow has further requirements. \nFor a detailed description of the authorization flow, see the [SLAS overview](https://developer.salesforce.com/docs/commerce/commerce-api/references?meta=shopper-login:Summary).\nA shopper token allows you to access the Shopper API endpoints of both OCAPI and the B2C Commerce API. These endpoints can be used to build headless storefronts and other applications.\nThe `ShopperToken` security scheme is a parent of other security schemes, such as `ShopperTokenTsob`. A Shopper API endpoint can require a specific child scheme (`ShopperTokenTsob`, for example) that cannot be accessed with a regular shopper token.\n"
      flows:
        clientCredentials:
          tokenUrl: https://{shortCode}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/token
          scopes:
            sfcc.shopper-experience: Shopper Experience scope READONLY
        authorizationCode:
          authorizationUrl: https://{short-code}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/authorize
          tokenUrl: https://{short-code}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/token
          scopes:
            sfcc.shopper-experience: Shopper Experience scope READONLY
  schemas:
    OrganizationId:
      description: An identifier for the organization the request is being made by
      example: f_ecom_zzxy_prd
      type: string
      minLength: 1
      maxLength: 32
    SiteId:
      minLength: 1
      maxLength: 32
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites
      example: RefArch
      type: string
    LanguageCountry:
      pattern: ^[a-z][a-z]-[A-Z][A-Z]$
      description: A concatenated version of the standard Language and Country codes, combined with a hyphen '`-`'.
      example: en-US
      type: string
    LanguageCode:
      pattern: ^[a-z][a-z]$
      description: A two letter lowercase language code conforming to the [ISO 639-1](https://www.iso.org/iso-639-language-codes.html) standard. Additionally, this may be used to submit requests with the header parameter `Accept-Language`, following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766).
      example: en
      type: string
    DefaultFallback:
      default: default
      description: A specialized value indicating the system default values for locales.
      example: default
      enum:
        - default
      type: string
    LocaleCode:
      description: A descriptor for a geographical region by both a language and country code. By combining these two, regional differences in a language can be addressed, such as with the request header parameter `Accept-Language` following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766). This can also just refer to a language code, also RFC 2616/1766 compliant, as a default if there is no specific match for a country. Finally, can also be used to define default behavior if there is no locale specified.
      oneOf:
        - $ref: '#/components/schemas/LanguageCountry'
        - $ref: '#/components/schemas/LanguageCode'
        - $ref: '#/components/schemas/DefaultFallback'
    Region:
      properties:
        id:
          maxLength: 256
          title: ID
          description: Region identifier.
          example: header
          type: string
        components:
          title: Components
          description: The components in the region.
          example:
            - id: iofwj38fhw3f
              typeId: commerce_assets.banner
              data:
                title: Products On Sale
                bannerImage: sale/topsellerPromo.jpg
              custom:
                thumbnail_full: http://static.myshop.com/sale/topsellerPromo.jpg
          type: array
          items:
            $ref: '#/components/schemas/Component'
      required:
        - id
      type: object
    Component:
      properties:
        id:
          maxLength: 256
          title: ID
          description: Component identifier.
          example: rfdvj4ojtltljw3
          type: string
        typeId:
          maxLength: 256
          title: Component Type ID
          description: Component type identifier.
          example: commerce_assets.carousel
          type: string
        data:
          title: Component Data
          description: The configuration data assigned to the component.
          example:
            title: Topseller
            category: topseller
          type: object
          additionalProperties: false
        custom:
          title: Custom Component Data
          description: Any custom data added by the custom code for this component.
          example:
            detailUrl: www.myshop.com/topseller
          type: object
          additionalProperties: false
        regions:
          title: Regions
          description: The regions (and their assigned components) for the component.
          example:
            - id: tiles
              components:
                - id: w3reÃ¶9wsjf3
                  typeId: commerce_assets.productTile
                  data:
                    product: iphone6
                - id: cgn8d4ngdl4n
                  typeId: commerce_assets.productTile
                  data:
                    product: iphone7
          type: array
          items:
            $ref: '#/components/schemas/Region'
      required:
        - id
        - typeId
      type: object
    Page:
      properties:
        id:
          maxLength: 256
          title: ID
          description: Page identifier.
          example: homepage
          type: string
        typeId:
          maxLength: 256
          title: Page Type ID
          description: Page type identifier.
          example: storePage
          type: string
        aspectTypeId:
          maxLength: 256
          title: Aspect Type ID
          description: The aspect type assigned to the page.
          example: pdpAspect
          type: string
        name:
          maxLength: 4000
          title: Page Name
          description: Display name of the page.
          example: Homepage
          type: string
        description:
          maxLength: 4000
          title: Page Description
          description: Description of the page.
          example: Home page of the storefront.
          type: string
        pageTitle:
          maxLength: 4000
          title: SEO Title
          description: The SEO title of the page.
          example: Homepage - My Shop
          type: string
        pageDescription:
          maxLength: 4000
          title: SEO Description
          description: The SEO description of the page.
          example: Get started shopping
          type: string
        pageKeywords:
          maxLength: 4000
          title: SEO Keywords
          description: The SEO keywords of the page.
          example: fashion, my shop
          type: string
        data:
          title: Page Data
          description: The configuration data assigned to the page.
          example:
            thumbnail: myshop.jpg
          type: object
          additionalProperties: false
        custom:
          title: Custom Page Data
          description: Any custom data added by the custom code for the page type.
          example:
            thumbnail_full: http://static.myshop.com/myshop.jpg
          type: object
          additionalProperties: false
        regions:
          title: Regions
          description: The regions (and their assigned components) for the page.
          example:
            - id: header
              components:
                - id: iofwj38fhw3f
                  typeId: commerce_assets.banner
                  data:
                    title: Products On Sale
                    bannerImage: sale/topsellerPromo.jpg
                  custom:
                    thumbnail_full: http://static.myshop.com/sale/topsellerPromo.jpg
            - id: main
              components:
                - id: rfdvj4ojtltljw3
                  typeId: commerce_assets.carousel
                  data:
                    title: Topseller
                    category: topseller
                  custom:
                    detailUrl: www.myshop.com/topseller
                  regions:
                    - id: tiles
                      components:
                        - id: w3reÃ¶9wsjf3
                          typeId: commerce_assets.productTile
                          data:
                            product: iphone6
                        - id: cgn8d4ngdl4n
                          typeId: commerce_assets.productTile
                          data:
                            product: iphone7
            - id: footer
              components: []
          type: array
          items:
            $ref: '#/components/schemas/Region'
      required:
        - id
        - typeId
      type: object
    PageResult:
      properties:
        data:
          title: Data
          description: List of pages.
          type: array
          items:
            $ref: '#/components/schemas/Page'
      required:
        - data
      type: object
    ErrorResponse:
      type: object
      additionalProperties: true
      properties:
        title:
          description: "A short, human-readable summary of the problem\ntype.  It will not change from occurrence to occurrence of the \nproblem, except for purposes of localization\n"
          type: string
          maxLength: 256
          example: You do not have enough credit
        type:
          description: |
            A URI reference [RFC3986] that identifies the
            problem type.  This specification encourages that, when
            dereferenced, it provide human-readable documentation for the
            problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
            this member is not present, its value is assumed to be
            "about:blank". It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: NotEnoughMoney
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: Your current balance is 30, but that costs 50
        instance:
          description: |
            A URI reference that identifies the specific
            occurrence of the problem.  It may or may not yield further
            information if dereferenced.  It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: /account/12345/msgs/abc
      required:
        - title
        - type
        - detail
  parameters:
    organizationId:
      description: An identifier for the organization the request is being made by
      name: organizationId
      in: path
      required: true
      example: f_ecom_zzxy_prd
      schema:
        $ref: '#/components/schemas/OrganizationId'
    categoryId:
      name: categoryId
      in: query
      description: Category identifier that is used for searching the page assignment. Must be provided if no `productId` is provided.
      required: false
      schema:
        maxLength: 256
        type: string
        example: home-clearance
    productId:
      name: productId
      in: query
      description: Product identifier that is used for searching the page assignment. Must be provided if no `categoryId` is provided.
      required: false
      schema:
        maxLength: 100
        type: string
        example: iphone11
    aspectTypeId:
      name: aspectTypeId
      in: query
      description: Aspect type identifier that is used for searching the page assignment in conjunction with either the `productId` or `categoryId`.
      required: true
      schema:
        maxLength: 256
        type: string
        example: pdp
    aspectAttributes:
      name: aspectAttributes
      in: query
      description: A JSON representation of aspect attributes. Each aspect attribute is a key/value pair. Aspect attributes serve as a runtime parameter contract between caller (for example, this API or the DWScript API) and callee (the page). This parameter must not contain more than 256 characters after URL decoding.
      required: false
      schema:
        type: string
        maxLength: 256
        example: |-
          {
            "product" : "iphone11",
            "breadcrumbCategory" : "home-clearance"
          }
    parameters:
      name: parameters
      in: query
      description: A free-form definition of parameters that influences the page rendering according to its implementation. This parameter must not contain more than 256 characters after URL decoding.
      required: false
      schema:
        maxLength: 256
        type: string
        example: refine=color,size;currency=USD;showNavigation=false
    siteId:
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites.
      name: siteId
      in: query
      required: true
      examples:
        SiteId:
          value: RefArch
      schema:
        $ref: '#/components/schemas/SiteId'
    locale:
      description: A descriptor for a geographical region by both a language and country code. By combining these two, regional differences in a language can be addressed, such as with the request header parameter `Accept-Language` following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766). This can also just refer to a language code, also RFC 2616/1766 compliant, as a default if there is no specific match for a country. Finally, can also be used to define default behavior if there is no locale specified.
      name: locale
      in: query
      examples:
        LanguageCountry:
          value: en-US
        CountryCode:
          value: US
      schema:
        $ref: '#/components/schemas/LocaleCode'
    pageId:
      name: pageId
      in: path
      description: Identifier for the requested page.
      required: true
      schema:
        maxLength: 256
        type: string
        example: homepage
  examples:
    PageResult:
      value:
        data:
          - id: homePpage
            typeId: storePage
            aspectTypeId: pdpAspect
            name: Homepage
            description: Home page of the storefront.
            pageTitle: Homepage - My Shop
            pageDescription: Get started shopping
            pageKeywords: fashion, my shop
            data:
              thumbnail: myshop.jpg
            custom:
              thumbnail_full: http://static.myshop.com/myshop.jpg
            regions:
              - id: header
                components:
                  - id: 2192f5b9aac0f2af2385f6f6b7
                    typeId: commerce_assets.banner
                    data:
                      title: Products On Sale
                      bannerImage: sale/topsellerPromo.jpg
                    custom:
                      thumbnail_full: http://static.myshop.com/sale/topsellerPromo.jpg
              - id: main
                components:
                  - id: 5c5ebbcd2aee1a67af519c83b5
                    typeId: commerce_assets.carousel
                    data:
                      title: Topseller
                      category: topseller
                    custom:
                      detailUrl: www.myshop.com/topseller
                    regions:
                      - id: tiles
                        components:
                          - id: d98a30dfe93715e3e6fc22a329
                            typeId: commerce_assets.productTile
                            data:
                              product: iphone6
                          - id: 43aa39896afb9292308181ce14
                            typeId: commerce_assets.productTile
                            data:
                              product: iphone7
          - id: detailpage
            typeId: storePage
            name: storepage
            description: A Store page
            pageTitle: A Store
            pageDescription: Buy in store
            pageKeywords: fashion, my shop, store
            data:
              thumbnail: mystore.jpg
    BusinessObjectIDInvalid:
      value:
        title: Business Object ID Invalid
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/business-object-id-invalid
        detail: At least one provided business object identifier was invalid. This means either none was provided at all or exclusiveness of multiple identifiers wasn't honored or the referenced business object didn't exist.
    AspectTypeNotFound:
      value:
        title: Aspect Type Not Found
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/aspect-type-not-found
        detail: No aspect type with ID 'pdp' was found in site 'RefArch'.
    Page:
      value:
        id: homepage
        typeId: storePage
        aspectTypeId: pdpAspect
        name: Homepage
        description: Home page of the storefront.
        pageTitle: Homepage - My Shop
        pageDescription: Get started shopping
        pageKeywords: fashion, my shop
        data:
          thumbnail: myshop.jpg
        custom:
          thumbnail_full: http://static.myshop.com/myshop.jpg
        regions:
          - id: header
            components:
              - id: 375b9107b067902827083772f9
                typeId: commerce_assets.banner
                data:
                  title: Products On Sale
                  bannerImage: sale/topsellerPromo.jpg
                custom:
                  thumbnail_full: http://static.myshop.com/sale/topsellerPromo.jpg
          - id: main
            components:
              - id: be1f331b92d8ad7e38e440e35d
                typeId: commerce_assets.carousel
                data:
                  title: Topseller
                  category: topseller
                custom:
                  detailUrl: www.myshop.com/topseller
                regions:
                  - id: tiles
                    components:
                      - id: 45af07459684e6db78990c5d05
                        typeId: commerce_assets.productTile
                        data:
                          product: iphone6
                      - id: df6e33766d90e7e205d109aa2f
                        typeId: commerce_assets.productTile
                        data:
                          product: iphone7
    AspectAttributeInvalid:
      value:
        title: Aspect Attribute Invalid
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/aspect-attribute-invalid
        detail: 'Aspect attribute value "5555" does not fulfill its respective definition {"id" : "foobar", "type" : "string","required" : "false"}'
    PageNotFound:
      value:
        title: Page Not Found
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/page-not-found
        detail: No visible page with ID 'homepage' was found in site 'RefArch'.
